import std/tables
import tnotifgen, std/options
import pkg/ybus/client/unix_sync

var client = newBusClient()
client.connect()

echo get client.notify("ybus", 0'u32, "org.gnome.Nautilus", "hello, ybus!", "this was sent through the autogenerated Notifications API bindings (bindgen)", @[], initTable[string, Variant](), 5000'i32)
