## Routines to generate XML code for the DBus Introspectable interface.
##
## Copyright (C) 2026 Trayambak Rai (xtrayambak@disroot.org)
import std/[strutils, tables]
import pkg/ybus/client/interfaces/define, pkg/ybus/wire/types

func toSigString(kind: VariantKind): string =
  case kind
  of VariantKind.String:
    "s"
  of VariantKind.Uint32:
    "u"
  of VariantKind.Int32:
    "i"
  of VariantKind.Array:
    "a"
  else:
    assert off, $kind
    newString(0)

func introspect*[T: object](iface: InterfaceDef[T]): string =
  ## Given an interface `iface`, generate its equivalent XML data for the Introspectable interface.
  var buffer = newStringOfCap(256) # TODO: better allocation prediction

  # Prelude
  buffer &=
    "<!DOCTYPE node PUBLIC \"-//freedesktop//DTD D-BUS Object Introspection 1.0//EN\" \"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd\">\n"

  when not defined(ybusDontMarkIntrospectionResult):
    buffer &= "<!-- Generated by ybus. -->\n"

  # Interface
  buffer &= "<interface name=\"$1\">\n" % [iface.name]
  for name, meth in iface.meths:
    buffer &= "  <method name=\"$1\">\n" % [name]

    for input in meth.signature.inputs:
      buffer &=
        "    <arg name=\"$1\" type=\"$2\" direction=\"in\"/>\n" %
        [input.name, toSigString(input.kind)]

    for output in meth.signature.outputs:
      buffer &=
        "    <arg name=\"$1\" type=\"$2\" direction=\"out\"/>\n" %
        [output.name, toSigString(output.kind)]

    buffer &= "  </method>\n"

  buffer &= "</interface>\n"
  ensureMove(buffer)
